### ISSUE TITLE
Writing to SPI Flash error

### ISSUE THREAD

**Issue by ohMoshko** [HarmonInstruments/CP2130#1]
Hi,

I am getting an error when running the example.cpp code. I had to change the timeout value in LibUSB.h in order to allow the erase_sector function to finish. I did not make any other changes. 
I am getting the following error when running the example:

![writeerror](https://user-images.githubusercontent.com/18669161/41380210-2d24e268-6f19-11e8-98ae-6ee937aacec7.png)

Seems like the erasing the sector succeeds but writing the data fails. When trying to read the data from the flash using a programmer I get 0xFF at the beginning, meaning that erasing the sector succeeded.

Is this something you ever encountered and you know what could be the problem?

Thanks,
Ohad

**Comment by dlharmon** [comment]
I ended up not using the CP2130, so this code hasn't seen much use here. The chip itself seems to be a bit buggy, needing some workarounds.

**Comment by ohMoshko** [comment]
Sounds good, so I will not use it. Thank you for the quick response.
